### PR TITLE
Fix Compilation with C++20

### PR DESCRIPTION
**Pull request by HazardyKnusperkeks**
Also you might want to replace the check with __cpp_concepts.

### CODE REVIEW

**Comment by rollbear** [comment]
Thanks. The problem is obvious, and the fix too, but do you mind telling me what compiler you ran into this with? I believe this is exercised in the CI build with clang++-15/libc++, clang++-15/libstdc++, gcc-12 and whatever version of MSVC is included in github-actions Visual Studio Enterprise 2022, but apparently it is not. I want to ensure that the CI builds catches this before merging.

**Comment by HazardyKnusperkeks** [comment]
I'm using GCC on Windows: gcc version 12.2.0 (Rev7, Built by MSYS2 project)
But the "normal" GCC and clang do not accept the code either: https://gcc.godbolt.org/z/77fMf1jno

I did not find the syntax on cppreference.com and didn't look into the standard, but as far as I know the requires clause has to come directly after the template declaration, or for functions before the semicolon/opening brace. I think the MSVC has a bug there.

**Comment by HazardyKnusperkeks** [comment]
I've never written CMake files. But when I read https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD and https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD_REQUIRED.html#prop_tgt:CXX_STANDARD_REQUIRED correctly, maybe you have to add that to your CI, or raise the minimum CMake version?

**Comment by rollbear** [comment]
OK, I know what the problem is now. In C++20, the macro `__cplusplus` is defined to be 202002L, and the comparison is with 202003L. :facepalm: Goes to show that I should've used the feature test macro instead, as you suggested. The reason the unit tests pass is that the check fails and it builds as if it was C++17. I'll try to get a brown paper bag release out later today.

**Comment by HazardyKnusperkeks** [comment]
> OK, I know what the problem is now. In C++20, the macro `__cplusplus` is defined to be 202002L, and the comparison is with 202003L. 🤦 Goes to show that I should've used the feature test macro instead, as you suggested. The reason the unit tests pass is that the check fails and it builds as if it was C++17. I'll try to get a brown paper bag release out later today.

Did not see that, then it seems I'm fixing the C++23 version. :)

**Comment by rollbear** [comment]
I just tagged version v10, which fixes this. The fix is ever so slightly different than yours, so I'm closing the PR now. Thank you for finding and reporting this.

**Pull request closed without merging**
