### PR TITLE
hash: Mark operator() noexcept where possible

### PR DESCRIPTION
**Pull request by HazardyKnusperkeks**
Found with GCC10 -Wnoexcept

### CODE REVIEW

**Comment by rollbear** [comment]
It looks like MSVC does not like this change much.

**Comment by rollbear** [comment]
Hmm, no, mea culpa, it looks like cirrus-ci has some problems with MSVC. Will have to investigate more, but the errors above say just about nothing at all, and compiling the test with your patch with MSVC at least builds on compiler explorer.

https://godbolt.org/z/zTGr76

**Comment by HazardyKnusperkeks** [comment]
That's fine. I have locally the commit and my colleagues won't need it until next year.

**Comment by rollbear** [comment]
Thank you!

**Pull request merged**
